on: [push]

permissions: write-all

jobs:
  hello_arborist:
    runs-on: ubuntu-latest
    name: Introduce the Arborist!
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Arborist
        id: arborist
        with:
          branches: '["main"]'
          min-approvals: 1
          enforce-admins: false
          team-roles: '{"FOLKS": "maintainers"}'
        uses: term-world/arborist@auto-allow-maintainers
    env:
      GITHUB_TOKEN: ${{ secrets.ARBORIST }}
