on: [push]

permissions: write-all

jobs:
  hello_arborist:
    runs-on: ubuntu-latest
    name: Introduce the Arborist!
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Arborist
        id: arborist
        with:
          branches: "['main', 'feedback']"
          min-approvals: 1
          bypass-user: dluman
        uses: term-world/arborist@v0.1.0
    env:
      GITHUB_TOKEN: ${{ secrets.ARBORIST }}
